import type { JsonObject, JsonValue } from '../types.js';
import { setAtPath } from '../utils/object-path.js';
import type { LoadedTemplate } from '../types.js';
import type { ConfigSession } from './session.js';

const SCHEMA_URL = 'https://developers.openai.com/codex/config-schema.json';
const DEPRECATED_PATH_PATTERNS = [
  /^experimental_use_unified_exec_tool$/,
  /^profiles\.[^.]+\.experimental_use_unified_exec_tool$/,
  /^tools\.web_search$/,
  /^profiles\.[^.]+\.tools_web_search$/,
  /^features\.web_search$/,
  /^features\.web_search_cached$/,
  /^features\.web_search_request$/,
];
const WARNING_STAGE_FEATURES = new Set([
  'apps',
  'apps_mcp_gateway',
  'artifact',
  'child_agents_md',
  'codex_git_commit',
  'default_mode_request_user_input',
  'image_detail_original',
  'image_generation',
  'js_repl',
  'js_repl_tools_only',
  'memories',
  'multi_agent',
  'plugins',
  'powershell_utf8',
  'prevent_idle_sleep',
  'realtime_conversation',
  'request_permissions',
  'responses_websockets',
  'responses_websockets_v2',
  'runtime_metrics',
  'shell_zsh_fork',
  'skill_env_var_dependency_prompt',
  'use_linux_sandbox_bwrap',
  'voice_transcription',
]);

export function generateConfigToml(template: LoadedTemplate, session: ConfigSession): string {
  const root: JsonObject = {};
  for (const entry of template.entries) {
    if (isDeprecatedCompatibilityPath(entry.path)) {
      continue;
    }
    const value = session.get(entry.path);
    if (value === undefined) {
      continue;
    }
    setAtPath(root, entry.path.split('.'), value);
  }

  if (shouldSuppressUnstableWarnings(session)) {
    setAtPath(root, ['suppress_unstable_features_warning'], true);
  }

  const rendered = serializeToml(root);
  return `#:schema ${SCHEMA_URL}\n# Generated by betterconfig.\n${rendered}`;
}

function isDeprecatedCompatibilityPath(path: string): boolean {
  return DEPRECATED_PATH_PATTERNS.some((pattern) => pattern.test(path));
}

function shouldSuppressUnstableWarnings(session: ConfigSession): boolean {
  if (session.isTouched('suppress_unstable_features_warning')) {
    return false;
  }

  for (const [path, value] of session.entries()) {
    if (value !== true) {
      continue;
    }
    const featureName = getFeatureName(path);
    if (featureName && WARNING_STAGE_FEATURES.has(featureName)) {
      return true;
    }
  }

  return false;
}

function getFeatureName(path: string): string | undefined {
  if (path.startsWith('features.')) {
    return path.slice('features.'.length);
  }
  const profileMatch = path.match(/^profiles\.[^.]+\.features\.(.+)$/);
  if (profileMatch) {
    return profileMatch[1];
  }
  return undefined;
}

// ---------------------------------------------------------------------------
// Custom TOML serializer
//
// @iarna/toml stringify indents nested table headers (e.g. "  [a.b]") which
// is invalid per the TOML spec and rejected by strict parsers.  It also
// misparses keys containing hyphens as dotted keys, creating corrupt output.
// This serializer always writes table headers at column 0, handles all scalar
// types, inline arrays/objects, and produces clean, spec-compliant output.
// ---------------------------------------------------------------------------

function serializeToml(root: JsonObject): string {
  const lines: string[] = [];
  emitTable(root, [], lines);
  return lines.join('\n') + '\n';
}

function emitTable(obj: JsonObject, keyPath: string[], lines: string[]): void {
  // First pass: scalar values and inline-able values at this level
  for (const [key, value] of Object.entries(obj)) {
    if (isSubTable(value)) {
      continue; // handle in second pass
    }
    lines.push(`${tomlKey(key)} = ${tomlValue(value)}`);
  }

  // Second pass: nested tables (ensures header comes after all scalars)
  for (const [key, value] of Object.entries(obj)) {
    if (!isSubTable(value)) {
      continue;
    }
    if (isArrayOfTables(value)) {
      for (const item of value as JsonObject[]) {
        lines.push('');
        lines.push(`[[${[...keyPath, key].map(tomlKey).join('.')}]]`);
        emitTable(item, [...keyPath, key], lines);
      }
    } else {
      lines.push('');
      lines.push(`[${[...keyPath, key].map(tomlKey).join('.')}]`);
      emitTable(value as JsonObject, [...keyPath, key], lines);
    }
  }
}

function isSubTable(value: JsonValue): boolean {
  if (!value || typeof value !== 'object') return false;
  if (isArrayOfTables(value)) return true;
  // Plain objects become [table] unless all values are scalars AND they can
  // be expressed inline.  We choose: always expand to [table] for readability.
  return !Array.isArray(value);
}

function isArrayOfTables(value: JsonValue): boolean {
  return (
    Array.isArray(value) &&
    value.length > 0 &&
    value.every((item) => item !== null && typeof item === 'object' && !Array.isArray(item))
  );
}

function tomlKey(key: string): string {
  // Quote keys that contain characters needing quoting (anything not bare)
  if (/^[A-Za-z0-9_-]+$/.test(key)) {
    return key;
  }
  return `"${key.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`;
}

function tomlValue(value: JsonValue): string {
  if (value === null) return 'null';
  if (typeof value === 'boolean') return value ? 'true' : 'false';
  if (typeof value === 'number') return String(value);
  if (typeof value === 'string') return tomlString(value);
  if (Array.isArray(value)) {
    if (value.length === 0) return '[]';
    const items = value.map((item) => tomlValue(item as JsonValue));
    const inline = `[ ${items.join(', ')} ]`;
    // Keep arrays inline (TOML allows it and it's more readable for short lists)
    return inline;
  }
  // Inline table for objects used as scalar values (e.g. set = { LANG = "..." })
  const pairs = Object.entries(value as JsonObject)
    .map(([k, v]) => `${tomlKey(k)} = ${tomlValue(v)}`)
    .join(', ');
  return `{ ${pairs} }`;
}

function tomlString(str: string): string {
  // Use basic string with escape sequences
  const escaped = str
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '\\r')
    .replace(/\t/g, '\\t');
  return `"${escaped}"`;
}

